index: README.md
style:
  favicon: sources/favicon-96x96.png
  themes:
    dark: sources/themes/dark.css
    light: sources/themes/light.css
  default theme: dark
folders:
  - sources
  - sources/themes
files:
  - README.md
  - README.de.md
  - README.en.md
  - sources/**
